### ISSUE TITLE
JPMS support broken in release 6.0.0

### ISSUE THREAD

**Issue by bjorndarri** [javalin/javalin-ssl#128]
It looks like JPMS support broke during the Kotlin refactor.

The module `io.javalin.community.ssl` is not found since there's no `module-info.class` in the jar file.

Having the `module-info.java` file under `src/main/kotlin` requires some build configuration, in order to have it compiled and added to the jar file. I've played with this a bit, trying out possible solutions from here:

[building-a-kotlin-java-9-project-with-gradle](https://stackoverflow.com/questions/47657755/building-a-kotlin-java-9-project-with-gradle)

but to no avail, I'm afraid I don't have the time to dig into this right now.

Some further reading on the Gradle forums:

[Java modules not getting added to the module path](https://github.com/gradle/gradle/issues/17271)

**Comment by zugazagoitia** [comment]
Definitely my fault for not considering it, and for not having a test for it. I'll research how I can fix it in Kotlin/gradle and how to [test](https://github.com/gradlex-org/java-module-testing) it.

I don't have much free time right now, but it must be available for the next Javalin release and earlier as a snapshot.
