### ISSUE TITLE
When will live reload of certificates be supported?

### ISSUE THREAD

**Issue by ascn17** [javalin/javalin-ssl#55]
Hello,
Live reload of certificates is a critical feature in our telco application where certificates are renewed frequently. I see this feature is planned for future but can you state approximate when in time this will be available?

We currently use Spark Java where this is possible to achieve by implementing the `spark.embeddedserver.Embeddedserver` interface. Does Javalin provide anything similar as a temporary workaround until this feature is released?

**Comment by zugazagoitia** [comment]
Update, we've got a [response](https://issues.sonatype.org/browse/OSSRH-84953?focusedCommentId=1229985&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1229985). I'm on CEST, they're on US/EST, if there's a solution by morning I'll have it released then.

**Comment by ascn17** [comment]
Many thanks for the good news!

**Comment by zugazagoitia** [comment]
I forgot to mention, the artifact is already available on [Reposilite](https://maven.reposilite.com/#/releases/io/javalin/community/ssl/ssl-plugin/5.3.0).

You can add the repo on maven: 
```xml
<repository>
  <id>reposilite-repository-releases</id>
  <name>Reposilite Repository</name>
  <url>https://maven.reposilite.com/releases</url>
</repository>
```

And Gradle 
```groovy
maven {
    url "https://maven.reposilite.com/releases"
}
```

**Comment by zugazagoitia** [comment]
The release is now live on Maven central :)

**Comment by ascn17** [comment]
Just saw the following statement: "**Client-side X.509 authentication is not supported.**"
Does this mean that mutual TLS (mTLS) doesn't work?

**Comment by zugazagoitia** [comment]
> Just saw the following statement: "**Client-side X.509 authentication is not supported.**"
> Does this mean that mutual TLS (mTLS) doesn't work?

That is correct, is this a feature you'd need? It's a little tricky from what I remember, but I could attempt to implement it. 

If you don't need to know the client certificate in the handler, just check it against a trust store while making the connection, it would be easy to do. 

How would you expect this implementation to look like?

**Comment by ascn17** [comment]
We have mTLS working fine with Spark Java and Jetty 9.x so this should not be hard to implement. We implement the EmbeddedSparkServer interface and use the Spark SslStores class. Something like this:

    private static class SslReloader implements PemFileWatcher.PemFileUserInterface, AutoCloseable {
        private SslStores sslStores;
        private SslContextFactory sslContextFactory;
        private PemFileWatcher pemThread = null;

        SslReloader(final SslStores sslStores, final SslContextFactory sslContextFactory) {
            this.sslStores = SslStores.create(sslStores.keystoreFile(), sslStores.keystorePassword(),
                    sslStores.certAlias(), sslStores.trustStoreFile(), sslStores.trustStorePassword(),
                    sslStores.needsClientCert());
            this.sslContextFactory = sslContextFactory;

            var file = Paths.get(this.sslStores.keystoreFile()).toFile();

            pemThread = new PemFileWatcher(file.getParent(), file.getName(), this);
            pemThread.start();
        }

**Comment by ascn17** [comment]
Created https://github.com/javalin/javalin-ssl/issues/56
