### ISSUE TITLE
Mention minimize config requirements in docs

### ISSUE THREAD

**Issue by dzikoysk** [javalin/javalin-ssl#59]
Pem certificates require several `org.bouncycastle` classes that are removed during minimize, because those are loaded dynamically at runtime. It might be a good idea to mention in docs that we need to preserve them in final jar.

In my case for **Gradle** (kts) and shadow plugin:

```kotlin
tasks.withType<ShadowJar> {
  minimize {
    exclude(dependency("org.bouncycastle:.*"))
  }
}
```

For **Maven** and the Shade plugin add the following filter to your configuration:

```xml
<filter>
   <artifact>org.bouncycastle:*</artifact>
   <includes>
       <include>**</include>
   </includes>
</filter>
```
* More info on: https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html

**Comment by dzikoysk** [comment]
`org.eclipse.jetty.http2:http2-hpack` has to be excluded as well:

* https://mvnrepository.com/artifact/org.eclipse.jetty.http2/http2-hpack

**Comment by zugazagoitia** [comment]
@tipsy please move it to the main repo so there is visibility
