### ISSUE TITLE
README中的例子有问题

### ISSUE THREAD

**Issue by MC-XiaoHei** [javalin/javalin-ssl#61]
在Configuration->Java代码块中，例子使用了**SSLConfig类中的loadPemFromPath**，但实际在5.3.2版本中这个方法**不存在**于SSLConfig类，应该使用**pemFromPath**，希望更改（也许Kotlin代码块中有同样的错误？）

**Comment by MC-XiaoHei** [comment]
In the Configuration ->Java code block, the example uses the loadPemFromPath in the SSLConfig class. However, in version 5.3.2, this method does not exist in the SSLConfig class. Instead, pemFromPath should be used. You want to change it (maybe there is the same error in the Kotlin code block?)

**Comment by zugazagoitia** [comment]
Indeed there is, thank you! Sorry for the late response.
