### ISSUE TITLE
Javalin-SSL added as dependency breaks jar main-class

### ISSUE THREAD

**Issue by Deamon12** [javalin/javalin-ssl#62]
As soon as I add this dependency to my gradle, my executable jar can no longer find the 'main-class' which prevents me from starting the jar executable.

`implementation 'io.javalin.community.ssl:ssl-plugin:5.2.0'`

The jar works fine when I just disable the dependency... So it seems something is going on with when the SSL dependency is built into the JAR and added to the class list?

I build the jar with this block:

`jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Class-Path': configurations.runtimeClasspath.files.collect { it.getName() }.join(' '),
                'Main-Class': 'Tester',
                'Version': createVersionName(baseVersion))
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    baseName 'Service'
}`

Thanks for the help

**Comment by zugazagoitia** [comment]
Could you provide both Manifests from the jars, both with and without the plugin? I won't be able to replicate this untill Sunday/Monday but I can try and help you in the meanwhile.
