### ISSUE TITLE
The type io.javalin.plugin.Plugin cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by cruzgsworks** [javalin/javalin-ssl#7]
I've tried following the initial guide but I'm getting this error. Any advice on this one?

_The type io.javalin.plugin.Plugin cannot be resolved. It is indirectly referenced from required .class files_
```
config.registerPlugin(new SSLPlugin(sslConf -> {
  sslConf.loadPemFromClasspath("...", "...");
}));
```

**Comment by zugazagoitia** [comment]
Don't expect this plugin to work until Javalin 5.0 is released, snapshots are undergoing breaking changes on a weekly basis.
