### ISSUE TITLE
Port `enableSslRedirects()` funcionality to `javalin-ssl` plugin configuration

### ISSUE THREAD

**Issue by dzikoysk** [javalin/javalin-ssl#70]
Plugin misses built-in configuration option to enable automatic redirects for HTTP connections. It might be a good idea to use `SslRedirectPlugin` under the hood, but it should also support custom SSL port configuration, so it's blocked by:

* https://github.com/javalin/javalin/issues/1834

Example use-case:

* https://github.com/dzikoysk/reposilite/issues/1751

**Comment by zugazagoitia** [comment]
How urgent is this? As I mentioned in your PR I can't work on it until Monday, but it's likely that it should work fine since you're using the port from the connectors. 

I could also implement this myself as a config option in the SSL plugin or just enable the plugin from my side. Let me know.

**Comment by dzikoysk** [comment]
It's not urgent, I'm using Javalin plugin atm to enable this functionally and that's why I've made PR with port adjustment. I just noticed it's not a part of ssl plugin config and I think it'd be nice if it could be a part of it someday in the future :)

**Comment by zugazagoitia** [comment]
I have two options, just enable the bundled plugin now that it's been merged or look into jetty's config to see if there's some option un their connectors, I remember something like it.
