### ISSUE TITLE
Upgrading from ssl-plugin:5.3.0 to 5.4.2

### ISSUE THREAD

**Issue by p4paul** [javalin/javalin-ssl#74]
I have a strange issue when I upgrade the `ssl-plugin:5.3.0` to `5.4.2`; the Swagger plugin no longer works (I get a 404 when fetching the webjars).

I'm using Java/Gradle (working configuration):
```
    // Javalin
    implementation 'io.javalin:javalin-bundle:5.4.2'
    implementation 'io.javalin.community.ssl:ssl-plugin:5.3.0'

    // Javalin OpenAPI (Swagger) plugin
    annotationProcessor("io.javalin.community.openapi:openapi-annotation-processor:5.4.2")
    implementation("io.javalin.community.openapi:javalin-openapi-plugin:5.4.2")
    implementation("io.javalin.community.openapi:javalin-swagger-plugin:5.4.2")
```

Removing the SSLPlugin registration makes no difference; it seems to be something about adding the `ssl-plugin:5.3.1` version and above?

I have looked at https://github.com/javalin/javalin-openapi/issues/115 and added the minimize exclude to my shadowJar, though this makes no difference?  I have CORS plugin and that is set to use `CorsPluginConfig::anyHost` 

Looking at the diff between 5.3.0 and 5.3.1 not much has changed?

**Comment by p4paul** [comment]
Update...

I hacked out `javalin-parent` (and added jetty-alpn-java-server) and this seems to work with 5.3.1....

```
dependencies {
    implementation 'org.eclipse.jetty:jetty-alpn-java-server:11.0.14'

    // Javalin
    implementation 'io.javalin:javalin-bundle:5.4.2'
    implementation 'io.javalin.community.ssl:ssl-plugin:5.3.1'

    // Javalin OpenAPI (Swagger) plugin
    annotationProcessor("io.javalin.community.openapi:openapi-annotation-processor:5.4.2")
    implementation("io.javalin.community.openapi:javalin-openapi-plugin:5.4.2")
    implementation("io.javalin.community.openapi:javalin-swagger-plugin:5.4.2")
    ...
}

configurations.all {
    ...
    exclude group: 'io.javalin', module: 'javalin-parent'
}
```

**Comment by zugazagoitia** [comment]
This is weird, I'll look at it and provide a fix if needed today.

**Comment by zugazagoitia** [comment]
It seems to be a dependency problem with the one defined by the OpenApi plugin and the one in `javalin-parent`. I'm working on it and a fix should be available in the next release.

**Comment by zugazagoitia** [comment]
Can you check if this is fixed in the [5.4.3 snapshot](https://github.com/javalin/javalin-ssl/releases/tag/5.4.3-SNAPSHOT)?

**Comment by p4paul** [comment]
Thank you; seems ok with:
```
    // Javalin
    implementation 'io.javalin:javalin-bundle:5.4.2'
    implementation 'io.javalin.community.ssl:ssl-plugin:5.4.3-SNAPSHOT'

    // Javalin OpenAPI (Swagger) plugin
    annotationProcessor("io.javalin.community.openapi:openapi-annotation-processor:5.4.2")
    implementation("io.javalin.community.openapi:javalin-openapi-plugin:5.4.2")
    implementation("io.javalin.community.openapi:javalin-swagger-plugin:5.4.2")
```

**Comment by zugazagoitia** [comment]
Great! This will be released in the next javalin/Javalin-ssl update then :)

**Comment by zugazagoitia** [comment]
Javalin `5.5.0` has been released! This change is now in the stable release.
