### ISSUE TITLE
Support HTTP/3

### ISSUE THREAD

**Issue by Mechite** [javalin/javalin-ssl#76]
**Describe the feature**
https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector-protocol-http3
Jetty has a full implementation of HTTP3 (the only other implementation I have seen since [flupke](https://github.com/ptrd/flupke)).

**Additional context**
I described this as a feature request on [Avaje Jex](https://github.com/avaje/avaje-jex/issues/46). Below I will quote the remainder of the comment for reference:

> ### Motivation
> - Better performance (difference would be negligible right now, but once the specification has been fully standardized, it will be many times better than HTTP/2, and HTTP3 is already being used to improve performance of sites with Cloudflare, and by e.g. Google in their core products to improve responsiveness)
> - On the road to supporting WebTransport as well (nobody has made a proper implementation of WebTransport in any language except Go, but for QUIC, [kwik](https://github.com/ptrd/kwik) exists, which [flupke](https://github.com/ptrd/flupke) uses as well)
>     - WebTransport will boost the performance of WebSockets by using QUIC as well, just like HTTP/3 is (HTTP/3 has other reasons to boost performance as well).
>     - WebTransport will finally rid people of the suffering of WebRTC, and allow for UDP data streaming for e.g. audio packets, game movement, etc, or for anything that requires this unsafe data streaming (and this will boost performance as well by increasing sheer throughput by not having the behemoth of dependencies on our backends, we could finally have the four wishes in our fever dreams of encryption, congestion control, CORS/consent and a damn simple specification).
> 
> ### Drawbacks
> - HTTP/3 has limited support, being majorly supported by Chrome (87+ on desktop, 111+ on Android) & Firefox (88+ on desktop, 110+ on Android), but with zero support from Safari (by extension, zero iOS support). While we could theoretically do the approach documented by Jetty with the alternate service header, I have mixed opinions about making this "temporary" solution __a default__ rather than enforcing first-class support for HTTP/3 on peoples' sites; you can see how on the [Cloudflare Quic test](https://cloudflare-quic.com/), your first connection ends up always being a HTTP/2 one before your client caches the support for HTTP/3. All supporting browsers support this header by default so this does work as a solution nontheless.
> - WebTransport (not included with this issue but again, for the future? Jex doesn't even have WebSockets yet...) is even less supported working only on Chrome (97+ on desktop, 111+ on Android); no other browsers support it.
> - Is there demand for this outside of me?

**Comment by zugazagoitia** [comment]
Seems like https://github.com/eclipse/jetty.project/pull/9490 might not go forward but https://github.com/eclipse/jetty.project/pull/9788 also fixes the issue with the HTTP/3 implementation in Jetty.

**Comment by zugazagoitia** [comment]
https://github.com/eclipse/jetty.project/pull/9788 was merged! HTTP/3 support is coming 🎉

**Comment by zugazagoitia** [comment]
## After further trial and investigation, I have decided to *NOT* implement this for now

Jetty's implementation of HTTP/3 and Quic is entirely based on a JNI binding to Quiche, which requires a completely different handling of cryptographic material than the standard library. Java unifies everything under the `SSLContext` class, used by both the HTTP/1.1 and HTTP/2 connectors in Jetty, as well as many other libraries. 

Integrating the HTTP/3 connector in the current state would suppose the integration of a different API with more limitations than the current ones, which I find not worth the chaos. If anyone would want to set it up manually, please refer to [Jetty's documentation on how to do it](https://eclipse.dev/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector-protocol-http3).

### If not now, when?

For HTTP/3 to be implemented one of two things would need to happen:

  - A proper, mature and pure Java implementation of the QUIC protocol that Jetty could build upon.
  - Native JDK support, providing a QUIC `Socket` like implementation. 

Regarding the second, I have exchanged a few emails with some developers at the JDK networking team, and while they are currently working on HTTP/3, there are no plans to expose the QUIC API for now. 

<details><summary>Email chain:</summary>
<p>

> Hi Alberto,
> 
> Actually, I'm just going to reply to you. We are working on HTTP/3 at the moment. We expect to publish a JEP to address this requirement, and the intention will be to support HTTP/3 in the new java.net.http client API only. Also, the QUIC layer will be internal and not exposed as a public API. I can't commit to any dates at this time.
> 
> Hope this is some help.
> 
> Regards,
> 
> Michael.
> 
> > On 26/09/2023 **:**, Alberto Zugazagoitia wrote:
> > Hi Michael,
> > 
> > Thank you for passing on my query to Daniel Fuchs. I appreciate your prompt response, and I look forward to hearing from him regarding the topic.
> > 
> > Best Regards,
> > Alberto
> > 
> > 
> > > On Tuesday, September 26, 2023 **:** CEST, Michael wrote:
> > > Hi Alberto
> > > 
> > > I have passed your query on to Daniel Fuchs who is coordinating our work in this area and will get back to you about it.
> > > 
> > > Michael
> > > 
> > > > On 25/09/2023 **:**, Alberto Zugazagoitia wrote:
> > > > Dear Michael,
> > > > 
> > > > I'm Alberto, a maintainer of the “Javalin" library, actively working on implementing HTTP/3 support within Javalin. I've recently searched for information regarding future QUIC support in OpenJDK but couldn't find any relevant developments.
> > > > 
> > > > Is there any plan within OpenJDK to implement native QUIC support? Currently, many projects, including Javalin, rely on external JNI libraries to handle HTTP/3, which can introduce complexities.
> > > > 
> > > > One challenge is the inability to seamlessly integrate QUIC into the existing Java SSL/TLS infrastructure, impacting usability and configuration. Native support in JDK could offer better integration, improved performance, and simplified configuration.
> > > > 
> > > > While I'm not experienced enough to contribute directly, I'm eager to follow any progress made in this area and offer support where possible.
> > > > 
> > > > Best Regards,
> > > > 
> > > > Alberto Zugazagoitia.
> > > 
> > 

</p>
</details>

**Comment by zugazagoitia** [comment]
@tipsy please move it to the main repo so there is visibility, thank you!
