### ISSUE TITLE
Enable JPMS for javalin-ssl

### ISSUE THREAD

**Issue by bjorndarri** [javalin/javalin-ssl#84]
Seeing that Javalin Core just got JPMS enabled ([Add JPMS to Core Javalin](https://github.com/javalin/javalin/pull/1908)) it would be great if the same could be done for this library.

The [sslcontext-kickstart](https://github.com/Hakky54/sslcontext-kickstart) library just got modularised ([Add support for java modules](https://github.com/Hakky54/sslcontext-kickstart/pull/333)) in version [8.0.0](https://github.com/javalin/javalin-ssl/pull/83), with minor breaking changes in package names.

I've implemented this in the [modules branch](https://github.com/bjorndarri/javalin-ssl/tree/modules) of a fork of mine.

I'm not planning on creating a pull-request, since this change seems quite trivial (and I had to add a jetbrains.annotations dependency, which makes me think I'm misundarstanding something :smile:), so just take this as an example of how this could be done.

**Comment by zugazagoitia** [comment]
Please do open the PR and I'll look at it by the end of the week!

**Comment by bjorndarri** [comment]
Here you go: #85

**Comment by zugazagoitia** [comment]
Closed by #85
